name: CrohnCare CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: Deploy Infrastructure (MongoDB & Backend)
    runs-on: ubuntu-latest
    env:
        TF_VAR_mongodb_atlas_public_key: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
        TF_VAR_mongodb_atlas_private_key: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
        TF_VAR_mongodb_atlas_project_id: ${{ secrets.MONGODB_ATLAS_PROJECT_ID }}
        TF_VAR_mongodb_atlas_org_id: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
        TF_VAR_mongodb_admin_password: ${{ secrets.MONGODB_ADMIN_PASSWORD }}
        TF_VAR_render_api_key: ${{ secrets.RENDER_API_KEY }}
        TF_VAR_render_service_id: ${{ secrets.RENDER_SERVICE_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Initialize Terraform
        run: |
          cd infra/terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd infra/terraform
          terraform plan

      - name: Terraform Apply
        run: |
          cd infra/terraform
          terraform apply -auto-approve

  backend:
    name: Deploy Backend (Node.js + Docker)
    needs: terraform  # Runs after Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t crohncare-backend:latest backend/

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"

  frontend:
    name: Deploy Frontend (React Native on Vercel)
    needs: backend  # Runs after backend deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
