name: CrohnCare CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    uses: ./.github/workflows/terraform-deploy.yml

  backend:
    needs: terraform
    uses: ./.github/workflows/backend-ci.yml

  frontend:
    needs: backend
    uses: ./.github/workflows/frontend-ci.yml
